services:
  - type: web
    name: insightboard-depengine-backend
    runtime: node
    rootDir: backend-ts
    buildCommand: npm install && npm run build
    startCommand: npm run prod
    envVars:
      - key: FRONTEND_ORIGIN
        value: https://insight-board-dependency-engine-mgxwws13h.vercel.app
